import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/Scaling';
import getFontFamily from '../../assets/fonts/helper';

export const CartStyle = StyleSheet.create({
  userNoLoggedIn: {
    backgroundColor: '#fff',
    padding: horizontalScale(15),
    borderWidth: horizontalScale(0.5),
    borderColor: '#ccc',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: horizontalScale(10),
    borderRadius: horizontalScale(20),
  },
  mainBtn: {
    width: '100%',
    padding: horizontalScale(10),
    backgroundColor: '#f9b000',
    marginVertical: verticalScale(20),
    borderRadius: horizontalScale(10),
    alignItems: 'center',
  },
  mainBtnText: {
    color: '#fff',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(16),
    textTransform: 'uppercase',
    fontFamily: getFontFamily('Roboto', 700),
    letterSpacing: horizontalScale(0.5),
  },
  describe: {
    color: '#6c6b6b',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14),
    fontFamily: getFontFamily('Roboto', 600),
    letterSpacing: horizontalScale(0.2),
    marginTop: verticalScale(3),
  },
  CountCart: {
    position: 'absolute',
    top: -5,
    right: -10,
    backgroundColor: '#f35c6e',
    paddingHorizontal: horizontalScale(5),
    paddingVertical: verticalScale(1),
    borderRadius: horizontalScale(10),
  },
  cartProd: {
    height: verticalScale(60),
    width: horizontalScale(60),
  },
  cartAddPrice: {
    display: 'flex',
    alignItems: 'center',
    columnGap: horizontalScale(7),
    flexDirection: 'row',
    marginTop: verticalScale(10),
  },
  cuttedPrice: {
    fontSize: scaleFontSize(11),
    textDecorationLine: 'line-through',
    color: '#000',
  },
  price: {
    fontSize: scaleFontSize(11),
    color: '#000',
    fontWeight: 500,
  },
  cartTrash: {
    borderWidth: 0.5,
    borderColor: '#8dc6ff',
    height: verticalScale(25),
    padding: horizontalScale(5),
    width: horizontalScale(27),
    borderRadius: horizontalScale(4),
    backgroundColor: '#e4f1fe',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemCount: {
    borderWidth: 0.5,
    borderColor: '#8dc6ff',
    height: verticalScale(25),
    width: horizontalScale(40),
    padding: horizontalScale(5),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: horizontalScale(4),
    backgroundColor: '#fff',
  },
  itemTotalAmount: {
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(18),
    fontWeight: 800,
  },
});
